### ISSUE TITLE
wofi build failing

### ISSUE THREAD

**Issue by johnodon** [luispabon/sway-ubuntu#6] opened 2021-09-04 11:47 UTC
Updated Ubuntu Desktop 21.04.

Build failing at this point.

```
cd wofi; hg pull; hg update;  sudo ninja -C build uninstall; sudo rm build -rf; meson build; ninja -C build; sudo ninja -C build install
/bin/sh: 1: cd: can't cd to wofi
abort: no repository found in '/home/pi/sway-ubuntu' (.hg not found)!
abort: no repository found in '/home/pi/sway-ubuntu' (.hg not found)!
ninja: Entering directory `build'
ninja: fatal: chdir to 'build' - No such file or directory

ERROR: Neither directory contains a build file meson.build.
ninja: Entering directory `build'
ninja: error: loading 'build.ninja': No such file or directory
ninja: Entering directory `build'
ninja: error: loading 'build.ninja': No such file or directory
make: *** [Makefile:247: wofi-build] Error 1

```

**Comment by johnodon** [comment] 2021-09-04 11:57
Not sure why cloning wofi is failing but if I run `hg clone https://hg.sr.ht/~scoopta/wofi` and then `make apps`, the build continues as expected,

**Comment by luispabon** [comment] 2021-09-04 14:20
That's weird, it does look like the first time you cloned all the repos for some reason wofi failed

**Comment by johnodon** [comment] 2021-09-04 15:40
> That's weird, it does look like the first time you cloned all the repos for some reason wofi failed

I literally copied the clone command from the Makefile and pasted it in the terminal and it ran fine.

**Comment by luispabon** [comment] 2021-09-04 15:49
I can't reproduce the issue on a pristine checkout:

![image](https://user-images.githubusercontent.com/6388823/132100423-9707998e-3a60-44ac-91f1-3b4b385e730c.png)

Is it possible that the first time repos were cloned you didn't have mercurial installed and only installed it later?

**Comment by luispabon** [comment] 2021-09-04 15:52
Provisionally fixed via 159047db90466b681bf88c7176493aafa549672d

**Comment by johnodon** [comment] 2021-09-04 15:55
> I can't reproduce the issue on a pristine checkout:
> 
> ![image](https://user-images.githubusercontent.com/6388823/132100481-bbe48551-506a-4753-b1b8-f0a95f45d06c.png)
> 
> Is it possible that the first time repos were cloned you didn't have mercurial installed and only installed it later? Hence making your manual `hg clone etc` command work.

I'll reinstall desktop and see if mercurial is already there (just to verify).  Either way your fix below should handle it.

**Comment by luispabon** [comment] 2021-09-04 15:57
Good stuff. I'll close this in the meantime. Pls reopen if necessary. Thanks for the reports 👍🏽

**Closed by luispabon** 2021-09-04 15:57 UTC

**Comment by johnodon** [comment] 2021-09-04 16:19
Confirmed...default install does not include mercurial.

Now that you have updated the makefile, I won't install it (or the missing libwayland libraries) and make sure everything works as expected.

**Comment by johnodon** [comment] 2021-09-04 16:37
Didn't know where to post this so I came back here...ran through a fresh install without any errors (mercurial, libwayland deps, swayimg, etc).

Thanks for your attention!

**Comment by luispabon** [comment] 2021-09-04 16:38
Excellent, thank you!
